#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sat Aug 17 14:05:03 2013

import wx

# begin wxGlade: extracode
# end wxGlade


class wxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.positionChoice = wx.Choice(self, -1, choices=[])
        self.teamChoice = wx.Choice(self, -1, choices=[])
        self.playerList_team = wx.ListCtrl(self, -1, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.franchiseChoice = wx.Choice(self, -1, choices=[])
        self.playerList_franchise = wx.ListCtrl(self, -1, style=wx.LC_REPORT | wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxFrame.__do_layout
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        franchiseSizer = wx.BoxSizer(wx.VERTICAL)
        teamSizer = wx.BoxSizer(wx.VERTICAL)
        teamSizer.Add(self.positionChoice, 0, wx.ALL | wx.EXPAND, 2)
        teamSizer.Add(self.teamChoice, 0, wx.ALL | wx.EXPAND, 2)
        teamSizer.Add(self.playerList_team, 1, wx.ALL | wx.EXPAND, 2)
        mainSizer.Add(teamSizer, 1, wx.ALL | wx.EXPAND, 10)
        franchiseSizer.Add(self.franchiseChoice, 0, wx.EXPAND, 0)
        franchiseSizer.Add(self.playerList_franchise, 1, wx.EXPAND, 0)
        mainSizer.Add(franchiseSizer, 1, wx.ALL | wx.EXPAND, 10)
        self.SetSizer(mainSizer)
        mainSizer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class wxFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    asxffl_draft_frame = wxFrame(None, -1, "")
    app.SetTopWindow(asxffl_draft_frame)
    asxffl_draft_frame.Show()
    app.MainLoop()
